image: lerk/android-ci

stages:
  - build
  -  test
  - artifacts

build_no_tests:
  stage: build
  script:
    - ./gradlew assemble

build_with_tests:
  stage: test
  script:
    - ./gradlew build

build_with_artifacts:
  stage: artifacts
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/app-debug.apk
  only:
    - tags