image: lerk/android-ci

stages:
  - build

build_with_tests:
  stage: build
  script:
    - ./gradlew build
  only:
    - master

build_with_artifacts:
  stage: build
  script:
    - ./gradlew assembleDebug
  artifacts:
    paths:
      - app/build/outputs/apk/app-debug.apk
  only:
    - tags